#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................. Conky colorN

usage() { usage: "rice $(basename $0) <color>"; }

COLORS=$PALETTE/.theme

[ $1 ] && grep "^$1.$(recipe theme/contrast)" $COLORS | cut -d= -f2 || usage

# kak: filetype=sh
