
# .......................................................... Syntax highlighting

#"attribute"                       =

#"type"                            =
#"type.builtin"                    =
#"type.enum"                       =
#"type.enum.variant"               =

#"constructor"                     =

"constant"                         = "constant"
#"constant.builtin"                =
#"constant.builtin.boolean"        =
#"constant.character"              =
#"constant.character.escape"       =
#"constant.numeric"                =
#"constant.numeric.integer"        =
#"constant.numeric.float"          =

"string"                           = "string"
#"string.regexp"                   =
#"string.special"                  =
#"string.special.path"             =
#"string.special.url"              =
#"string.special.symbol"           =

"comment"                          = "comment"
#"comment.line"                    =
#"comment.block"                   =
#"comment.block.documentation"     =

"variable"                         = "variable"
#"variable.builtin"                =
#"variable.parameter"              =
#"variable.other"                  =
#"variable.other.member"           =

#"label"                           =

#"punctuation"                     =
#"punctuation.delimiter"           =
#"punctuation.bracket"             =
#"punctuation.special"             =

"keyword"                          = { fg = "keyword", modifiers = ["bold"] }
#"keyword.control"                 =
#"keyword.control.conditional"     =
#"keyword.control.repeat"          =
#"keyword.control.import"          =
#"keyword.control.return"          =
#"keyword.control.exception"       =
#"keyword.operator"                =
#"keyword.directive"               =
#"keyword.function"                =
#"keyword.storage"                 =
#"keyword.storage.type"            =
#"keyword.storage.modifier"        =

"operator"                         = { fg = "operator", modifiers = ["bold"] }

"function"                         = { fg = "function", modifiers = ["bold"] }
#"function.builtin"                =
#"function.method"                 =
#"function.macro"                  =
#"function.special"                =

#"tag"                             =
#"tag.builtin"                     =

#"namespace"                       =

#"special"                         =

#"markup"                          =
"markup.heading"                   = { fg = "string", modifiers = ["bold"] }
"markup.heading.marker"            = { fg = "selection", modifiers = ["bold"] }
#"markup.heading.1"                =
#"markup.heading.2"                =
#"markup.heading.3"                =
#"markup.heading.4"                =
#"markup.heading.5"                =
#"markup.heading.6"                =
#"markup.list"                     =
#"markup.list.unnumbered"          =
#"markup.list.numbered"            =
#"markup.list.checked"             =
#"markup.list.unchecked"           =
"markup.bold"                      = { modifiers = ["bold"] }
"markup.italic"                    = { modifiers = ["italic"] }
"markup.strikethrough"             = { modifiers = ["crossed_out"] }
"markup.link"                      = "string"
"markup.link.url"                  = { fg = "selection", modifiers = ["underlined"] }
#"markup.link.label"               =
#"markup.link.text"                =
#"markup.quote"                    =
#"markup.raw"                      =
#"markup.raw.inline"               =
#"markup.raw.block"                =

#"diff"                            =
"diff.plus"                        = "plus"
"diff.minus"                       = "foreground"
"diff.delta"                       = "delta"
#"diff.delta.moved"                =

# .................................................................... Interface

#"markup"                          =
#"markup.normal"                   =
#"markup.normal.completion"        =
#"markup.normal.hover"             =
#"markup.heading"                  =
#"markup.heading.completion"       =
#"markup.heading.hover"            =
#"markup.raw"                      =
#"markup.raw.inline"               =
#"markup.raw.inline.completion"    =
#"markup.raw.inline.hover"         =

"ui.background"                    = { bg = "background" }
#"ui.background.separator"         =
"ui.cursor"                        = { bg = "cursor", fg = "foreground" }
#"ui.cursor.normal"                =
#"ui.cursor.insert"                =
#"ui.cursor.select"                =
#"ui.cursor.match"                 =
#"ui.cursor.primary"               =
#"ui.cursor.primary.normal"        =
#"ui.cursor.primary.insert"        =
#"ui.cursor.primary.select"        =
#"ui.debug.breakpoint"             =
#"ui.debug.active"                 =
#"ui.gutter"                       =
#"ui.gutter.selected"              =
#"ui.highlight.frameline"          =
"ui.linenr"                        = "linenr"
"ui.linenr.selected"               = "string"
"ui.statusline"                    = { bg = "background", fg = "statusline" }
#"ui.statusline.inactive"          =
#"ui.statusline.normal"            =
#"ui.statusline.insert"            =
#"ui.statusline.select"            =
#"ui.statusline.separator"         =
"ui.popup"                         = { bg = "popup", fg = "text" }
#"ui.popup.info"                   =
#"ui.window"                       =
"ui.help"                          = { bg = "background", fg = "text", modifiers = ["bold"] }
"ui.text"                          = "text"
"ui.text.focus"                    = { bg = "cursor", fg = "foreground" }
#"ui.text.inactive"                =
#"ui.text.info"                    =
#"ui.virtual.ruler"                =
#"ui.virtual.whitespace"           =
#"ui.virtual.indent-guide"         =
#"ui.virtual.inlay-hint"           =
#"ui.virtual.inlay-hint.parameter" =
#"ui.virtual.inlay-hint.type"      =
#"ui.virtual.wrap"                 =
"ui.menu"                          = { bg = "popup", fg = "text" }
"ui.menu.selected"                 = { bg = "cursor", fg = "foreground"  }
#"ui.menu.scroll"                  =
"ui.selection"                     = { bg = "selection", fg = "background" }
#"ui.selection.primary"            =
#"ui.highlight"                    =
#"ui.cursorline.primary"           =
#"ui.cursorline.secondary"         =
#"ui.cursorcolumn.primary"         =
#"ui.cursorcolumn.secondary"       =
#"warning"                         =
#"error"                           =
"info"                             = "ltex"
#"hint"                            =
"diagnostic"                       = { bg = "popup", fg = "text" }
#"diagnostic.hint"                 =
#"diagnostic.info"                 =
#"diagnostic.warning"              =
#"diagnostic.error"                =

[palette]

background                         = "#f7f3ee"  # light grayish orange
foreground                         = "#263238"  # very dark grayish blue (black)
selection                          = "#0087af"  # dark cyan (blue)
cursor                             = "#20fccf"  # vivid cyan (iawriter)

ltex                               = "#fa8c69"  # salmon (pink)
plus                               = "#a3d5e4"  # soft cyan
delta                              = "#fdd3c6"  # salmon (pink)
linenr                             = "#cfd8dc"  # light grayish blue

popup                              = "#ffe5b4"  # peach (orange)
text                               = "#3e525b"  # very dark grayish blue
statusline                         = "#78a0a2"  # mostly desaturated dark cyan

comment                            = "#d5b875"  # slightly desaturated orange
constant                           = "#008b8b"  # dark cyan (teal)
function                           = "#485f6a"  # very dark grayish blue
# keyword                          = "#bf450c"  # strong orange
# operator                         = "#008b8b"  # dark cyan (teal)
keyword                            = "#0069af"  # dark blue
operator                           = "#bf450c"  # strong orange
string                             = "#a1462a"  # desaturated strong red
variable                           = "#59837c"  # mostly desaturated dark cyan - lime green
