#!/bin/sh
# sdothum - 2016 (c) wtfpl
# SEE: /etc/runit/core-services/01-static-devnodes.sh
# SEE: /etc/runit/core-services/02-kmods.sh
. /etc/runit/functions
[ -z "${container+x}" ] || export IS_CONTAINER=1
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

# Some kernel modules must be loaded before starting udev(7).
# Load them by looking at the output of `kmod static-nodes`.

for f in $(kmod static-nodes -f devname 2>/dev/null|cut -d' ' -f1); do
	modprobe -bq $f 2>/dev/null
done

[ -n "$IS_CONTAINER" ] && return 0
# Do not try to load modules if kernel does not support them.
[ ! -e /proc/modules ] && return 0

msg "Loading kernel modules..."
modules-load -v | tr '\n' ' ' | sed 's:insmod [^ ]*/::g; s:\.ko\(\.gz\)\? ::g'
echo

# kak: filetype=sh
