#!/bin/sh
# sdothum - 2016 (c) wtfpl
. /etc/runit/functions

. /etc/dinit.d/config/network.conf

if [ -z "$GATEWAY" ]; then
	set -- $(ip route show | grep default)
	GATEWAY="$3"
fi
while ! ping -W 1 -c 1 $GATEWAY; do
msg "Waiting for network"
sleep 0.1
done
msg "Network responding"
exit 0

# kak: filetype=sh
