#!/bin/sh
# sdothum - 2016 (c) wtfpl
# SEE: /etc/runit/shutdown.d/30-seedrng.sh
# SEE: /etc/runit/core-services/05-misc.sh
. /etc/runit/functions
[ -r /etc/rc.conf ] && . /etc/rc.conf
[ -z "${container+x}" ] || export IS_CONTAINER=1

case $1 in
	stop )
		# The system is being shut down
		if [ -z "$IS_CONTAINER" ]; then
			msg "Saving random number seed..."
			seedrng
		fi
		;;

	*    )
		install -m0664 -o root -g utmp /dev/null /run/utmp
		halt -B  # for wtmp

		if [ -z "$IS_CONTAINER" ]; then
			msg "Seeding random number generator..."
			seedrng || true
		fi

		msg "Setting up loopback interface..."
		ip link set up dev lo

		[ -r /etc/hostname ] && read -r HOSTNAME < /etc/hostname
		if [ -n "$HOSTNAME" ]; then
			msg "Setting up hostname to '${HOSTNAME}'..."
			printf "%s" "$HOSTNAME" > /proc/sys/kernel/hostname
		else
			msg "Didn't setup a hostname!"
		fi

		if [ -n "$TIMEZONE" ]; then
			msg "Setting up timezone to '${TIMEZONE}'..."
			ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
		fi
		;;
esac

# kak: filetype=sh
