#!/bin/sh
# sdothum - 2016 (c) wtfpl
# SEE: /etc/runit/core-services/03-filesystems.sh
. /etc/runit/functions

msg "Mounting rootfs read-write..."
LIBMOUNT_FORCE_MOUNT2=always mount -o remount,rw / || emergency_shell
