#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="focus/next $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................. Focus window

xdotool key Super+Tab  # find a window after a window close or hide

# vim: set ft=sh: #
