#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="focus/next $@" . $PARENT

# Mail
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................. Focus window

# see 2bwm config.h
xdotool key Super+Tab

# vim: set ft=sh: #
