# ───────────────────────── = (align template)

theme                       = "chroma"

# ....................................................................... Editor

[editor]
# ───────────────────────── = (align template)
auto-completion             = true
auto-format                 = false
auto-info                   = true
auto-pairs                  = false
auto-save                   = true
bufferline                  = "never"
color-modes                 = false
completion-replace          = false
completion-trigger-len      = 1
cursorcolumn                = false
cursorline                  = false
gutters                     = ["spacer", "spacer", "spacer", "spacer", "spacer", "diagnostics", "spacer", "spacer", "line-numbers", "spacer", "spacer", "diff", "spacer", "spacer", "spacer"]
idle-timeout                = 250
line-number                 = "relative"
middle-click-paste          = true
mouse                       = true
rulers                      = []
scroll-lines                = 3
scrolloff                   = 5
shell                       = ["fish", "-c"]
text-width                  = 80
true-color                  = false
undercurl                   = false
workspace-lsp-roots         = []

[editor.statusline]
# ───────────────────────── = (align template)
separator                   = "│"
mode.normal                 = ""
mode.insert                 = ""
mode.select                 = ""
left                        = ["spacer", "file-modification-indicator", "file-base-name", "spacer", "file-type", "spacer", "file-encoding"]
center                      = ["selections", "spacer", "spacer", "spacer", "mode", "spacer", "spacer", "spacer", "position" ]
right                       = ["diagnostics", "spacer", "spacer", "position-percentage", "spacer", "spacer", "spinner", "spacer", "spacer"]

[editor.lsp]
# ───────────────────────── = (align template)
enable                      = true
display-messages            = false
auto-signature-help         = true
display-inlay-hints         = false
display-signature-help-docs = true
snippets                    = true

[editor.cursor-shape]
# ───────────────────────── = (align template)
insert                      = "bar"
normal                      = "block"
select                      = "underline"

[editor.file-picker]
# ───────────────────────── = (align template)
hidden                      = false
follow-symlinks             = true
deduplicate-links           = true
parents                     = true
ignore                      = true
git-ignore                  = true
git-global                  = true
git-exclude                 = true
max-depth                   = 10

[editor.search]
# ───────────────────────── = (align template)
smart-case                  = true
wrap-around                 = true

# or control each character
[editor.whitespace.render]
# ───────────────────────── = (align template)
space                       = "none"
tab                         = "none"
newline                     = "none"

[editor.whitespace.characters]
# ───────────────────────── = (align template)
space                       = "·"
nbsp                        = "⍽"
tab                         = "→"
newline                     = "↩"  # "⏎"
tabpad                      = "·"

[editor.indent-guides]
# ───────────────────────── = (align template)
render                      = true
character                   = "┊"  # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
skip-levels                 = 1

[editor.soft-wrap]
# ───────────────────────── = (align template)
enable                      = true
max-wrap                    = 20
max-indent-retain           = 40
wrap-indicator              = "  ↪ "
wrap-at-text-width          = false

# ..................................................................... Keybinds

[keys.normal]
# ───────────────────────── = (align template)
esc                         = ["collapse_selection", "keep_primary_selection"]

A-backspace                 = "goto_last_accessed_file"
A-ret                       = "goto_next_buffer"
C-o                         = ":config-open"
C-r                         = ":config-reload"
Z                           = { Z = ":wqa!" }

C-a                         = "select_all"
C-h                         = "select_prev_sibling"
C-j                         = "shrink_selection"
C-k                         = "expand_selection"
C-l                         = "select_next_sibling"

"{"                         = ["goto_prev_paragraph", "collapse_selection"]
"}"                         = ["goto_next_paragraph", "collapse_selection"]
0                           = "goto_line_start"
"$"                         = "goto_line_end"
"^"                         = "goto_first_nonwhitespace"
G                           = "goto_file_end"
"%"                         = "match_brackets"

ret                         = ["move_line_down", "goto_first_nonwhitespace"]        # maps the enter key to move to start of next line
# A-d                       = "delete_char_backward"
D                           = "delete_char_backward"
# C-r                       = ["match_brackets", "select_textobject_inner", ":reflow"]
g                           = { a = "code_action", o = "goto_last_accessed_file" }  # maps `ga` to show possible code actions
C-n                         = ["move_line_down", "scroll_down"]
C-p                         = ["move_line_up", "scroll_up"]
V                           = ["goto_line_start", "select_mode", "goto_line_end_newline"]
X                           = "extend_line_above"

# to circumvent multi-cursor single line register yanks
# p                         = "paste_clipboard_after"
# P                         = "paste_clipboard_before"
# y                         = "yank_to_clipboard"
# Y                         = "yank_joined_to_clipboard"
# R                         = "replace_selections_with_clipboard"
# d                         = ["yank_to_clipboard", "delete_selection_noyank"]
# D                         = ["yank_joined_to_clipboard", "delete_selection_noyank"]

[keys.normal."+"]
# ───────────────────────── = (align template)
# text insertion
d = ":insert-output date '+## %A, %d %B %Y' | tr '[:upper:]' '[:lower:]'"
t = ":insert-output timestamp | nocolor"

# # post snippet action ";;di" to insert text
# i = [":insert-output echo '![;](/images/;.jpg)'", "goto_line_start", "find_next_char"]
# # bash usage: snippets
# u = [":insert-output echo 'usage() { usage: \"$(basename $0) ;\"; exit 1; }'", "goto_line_start", "find_next_char"]
# U = [":insert-output echo 'usage() { echo \"$(basename $0) ;\" | usage:<>exit 1<}' | tr '>' '\t' | tr '<' '\n'", "move_visual_line_up", "move_visual_line_up", "goto_line_start", "find_next_char"]

[keys.select]
# ───────────────────────── = (align template)
esc                         = ["collapse_selection", "keep_primary_selection", "normal_mode"]

"{"                         = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}"                         = ["extend_to_line_bounds", "goto_next_paragraph"]
0                           = "goto_line_start"
"$"                         = "goto_line_end"
"^"                         = "goto_first_nonwhitespace"
G                           = "goto_file_end"


D                           = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C                           = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%"                         = "match_brackets"
S                           = "surround_add" # Basically 99% of what I use vim-surround for
u                           = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U                           = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

i                           = "select_textobject_inner"
a                           = "select_textobject_around"

tab                         = ["insert_mode", "collapse_selection"]  # tab is read by most terminal editors as "C-i"
C-a                         = ["append_mode", "collapse_selection"]

k                           = ["extend_line_up", "extend_to_line_bounds"]
j                           = ["extend_line_down", "extend_to_line_bounds"]

d                           = ["yank_main_selection_to_clipboard", "delete_selection"]
x                           = ["yank_main_selection_to_clipboard", "delete_selection"]
y                           = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y                           = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p                           = "replace_selections_with_clipboard"

[keys.insert]
# ───────────────────────── = (align template)
esc                         = ["collapse_selection", "normal_mode"]

ret                         = ["insert_newline", "commit_undo_checkpoint"]          # a more granular history
C-space                     = "completion"
# A-h                       = "move_char_left"
# j                         = { k = "normal_mode" }                                 # maps qwerty `jk` to exit insert mode
# A-j                       = "move_line_down"
# A-k                       = "move_line_up"
# A-l                       = "move_char_right"
A-O                         = "open_above"
A-o                         = "open_below"
