# ────────────────────────── = (align template)

# .......................................................... Additional grammars

# hx --grammar fetch
# hx --grammar build
# Note: must also download/make and copy tree-sitter-[language]/queries/ to $HOME/.config/helix/runtime/queries/[language]

[[grammar]]
name                         = "vim"
source                       = { git = "https://github.com/neovim/tree-sitter-vim", rev = "26b1aea3b3a5dae31f784a1204205fd57f2b82b5" }

# ............................................................. Language servers

[language-server.bash-language-server]
command                      = "bash-language-server"

[language-server.buffer-language-server]
command                      = "buffer-language-server"

[language-server.ltex-ls]
command                      = "/opt/ltex-ls/bin/ltex-ls"

[language-server.ltex-ls.config]
# ltex.completionEnabled     = true
ltex.language                = "en-US"
ltex.disabledRules           = { "en-US" = [ "PROFANITY" ] }
# user spelling dictionary languages:spelling.toml inserted here ...............
ltex.dictionary              = { "en-US" = [
"Calibre",
"ebook",
"econtent",
"eink",
"epub",
"ereader",
"ereaders",
"ereading",
"frontlight",
"graal",
"groot",
"kepub",
"Kindle",
"Kobo",
"kobopatch",
"kobopatches",
"koreader",
"mobi",
"pdf",
"warmlight"
] }

# [language-server.scls]
# command                    = "simple-completion-language-server"
# config                     = { max_completion_items = 20, snippets_first = true }

# [language-server.scls.environment]
# RUST_LOG                   = "debug,simple-completion-langauge-server=debug"
# LOG_FILE                   = "/tmp/completion.log"

[language-server.solargraph]
command                      = "solargraph"

[language-server.vimls]
command                      = "/usr/local/bin/vim-language-server"
args                         = ["--stdio"]
filetypes                    = ["vim"]

[language-server.vimls.initializationOptions]
isNeovim                     = false
iskeyword                    = "@,48-57,_,192-255,-#"
vimruntime                   = "/usr/share/vim/vim90"
runtimepath                  = ""
diagnostic                   = { enable = true }
indexes                      = { runtimepath = true, gap = 100, count = 3, projectRootPatterns  = ["", ".git", "autoload", "plugin"] }
suggest                      = { fromVimruntime = true, fromRuntimepath = false }

# ............................................................. Language configs

[[language]]
name                         = "bash"
comment-token                = "#"
file-types                   = ["sh", { suffix = "functions" }]
indent                       = { tab-width = 3, unit = "\t" }
language-servers             = ["bash-language-server", "buffer-language-server"]
roots                        = []
scope                        = "source.sh"
shebangs                     = [ "sh", "ash", "bash", "dash" ]
text-width                   = 80

[[language]]
name                         = "conf"
comment-token                = "#"
file-types                   = ["conf"]
indent                       = { tab-width = 3, unit = "\t" }
language-servers             = ["buffer-language-server"]
roots                        = []
scope                        = "source.conf"
text-width                   = 80

[[language]]
name                         = "c"
comment-token                = "//"
file-types                   = ["c", "h", "cpp"]
indent                       = { tab-width = 3, unit = "\t" }
language-servers             = ["clangd", "buffer-language-server"]
roots                        = []
scope                        = "source.c"
text-width                   = 80

[[language]]
name                         = "json"
file-types                   = ["json"]
indent                       = { tab-width = 3, unit = "\t" }
language-servers             = ["vscode-json-language-server", "buffer-language-server"]
roots                        = []
scope                        = "source.json"
text-width                   = 80

[[language]]
name                         = "mail"
comment-token                = "#"
file-types                   = ["eml"]
indent                       = { tab-width = 3, unit = "   " }
language-servers             = ["ltex-ls", "buffer-language-server"]
roots                        = []
scope                        = "source.eml"
soft-wrap.wrap-at-text-width = true
text-width                   = 80

[[language]]
name                         = "markdown"
file-types                   = ["md", "mkd", "txt", "wiki"]
indent                       = { tab-width = 3, unit = "   " }
# language-servers           = [{ name = "marksman" }]  # supplanted by ltex-ls!
language-servers             = ["ltex-ls", "buffer-language-server"]
roots                        = []
scope                        = "source.md"
soft-wrap.wrap-at-text-width = true
text-width                   = 80

[[language]]
name                         = "perl"
comment-token                = "#"
file-types                   = ["pl" ]
indent                       = { tab-width = 3, unit = "\t" }
roots                        = []
scope                        = "source.pl"
text-width                   = 80

[[language]]
name                         = "toml"
comment-token                = "#"
file-types                   = ["toml"]
indent                       = { tab-width = 3, unit = "\t" }
language-servers             = ["taplo", "buffer-language-server"]
roots                        = []
scope                        = "source.toml"
text-width                   = 80

[[language]]
name                         = "ruby"
comment-token                = "#"
file-types                   = ["rb" ]
indent                       = { tab-width = 3, unit = "\t" }
language-servers             = ["solargraph", "buffer-language-server"]
roots                        = []
scope                        = "source.rb"
text-width                   = 80

[[language]]
name                         = "vim"
comment-token                = "\""
file-types                   = ["vim" ]
grammar                      = "vim"
indent                       = { tab-width = 3, unit = "\t" }
language-servers             = ["vimls", "buffer-language-server"]
roots                        = []
scope                        = "source.vim"
text-width                   = 80

# ────────────────────────── = (align template)
