
[[language]]
name                         = "bash"
comment-token                = "#"
file-types                   = ["sh", { suffix = "functions" }]
indent                       = { tab-width = 3, unit = "\t" }
roots                        = []
scope                        = "source.sh"
shebangs                     = [ "sh", "ash", "bash", "dash" ]
text-width                   = 80

[[language]]
name                         = "mail"
comment-token                = "#"
file-types                   = ["eml"]
indent                       = { tab-width = 3, unit = "   " }
language-servers             = [{ name = "ltex-ls" }]
roots                        = []
scope                        = "source.eml"
soft-wrap.wrap-at-text-width = true
text-width                   = 80

[[language]]
name                         = "markdown"
file-types                   = ["md", "mkd", "txt", "wiki"]
indent                       = { tab-width = 3, unit = "   " }
# language-server            = { command = "marksman" }  # supplanted by ltex-ls!
language-servers             = [{ name = "ltex-ls" }]
roots                        = []
scope                        = "source.md"
soft-wrap.wrap-at-text-width = true
text-width                   = 80

[[language]]
name                         = "ruby"
comment-token                = "#"
file-types                   = ["rb" ]
indent                       = { tab-width = 3, unit = "\t" }
roots                        = []
scope                        = "source.rb"
text-width                   = 80

[language-server.ltex-ls]
command                      = "/opt/ltex-ls/bin/ltex-ls"

[language-server.ltex-ls.config]
ltex.language                = "en-US"
ltex.disabledRules           = { "en-US" = [ "PROFANITY" ] }
ltex.dictionary              = { "en-US" = [
"ebook",
"eink",
"ereader",
"ereaders",
"ereading",
"frontlight",
"graal",
"groot",
"Kindle",
"Kobo",
"kobopatch",
"kobopatches",
"koreader",
"warmlight"
] }
