#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... Autostart

sudo iwconfig wlp9s0 power off  # disable powersave mode (to prevent sleeping connection)

restore root
conky clock auto
restore unclutter
displaycal3            # load color profile

imwheel -kill          # set trackball scrollwheel speed
recipe -d pavucontrol  # hide pavucontrol SEE: rulerrc
pulse
udev

desktop $(chef desktop "DESK")
recipe -q cbonsai && cbonsai
recipe -q term    && term term $(recipe term)

# issue running as runit service
if void 'runit' ;then
	!p nzbget && nzbget --daemon
	!p sonarr && sudo /bin/su - sonarr -c '/usr/lib/sonarr/Sonarr/Sonarr -s localhost:8989 -no-browser -data=/var/lib/sonarr' >/dev/null 2>&1 &
fi

restore panel  # postponed as long as possible to avoid dirty trace messages
exists mpd || exit

sleep 1        # settle pipewire for mpd server connection
dbus-run-session mpd /home/shum/.config/mpd/mpd.conf 2>/dev/null
[ -e /tmp/nicotine-plus ] || { make_install nicotine-plus; touch /tmp/nicotine-plus; }  # using nightly build

nicotine -s &
if mpc queued >/dev/null ;then
	(sleep 3; for i in play toggle toggle ;do mpc $i >/dev/null ;done; mpc:settings) &        # mpd tickling required to connect to pipewire
else
	piano  # nano hi resolution stream
fi

# kak: filetype=sh
