#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="desktop $@" . $PARENT

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................. Group operations

# Usage: desktop <msg> SEE: functions/desktop
#                where, 0-9   -> desktop focus <msg>
#                       -1/+1 -> desktop focus <msg> (relative)

# NOTE: waitron group handling deficiencies (quirks) and extensions are handled here
# HACK: waitron group_toggle/_activate does not restore the group window stack order (focused window)

CURRENT=$GROUP/current
LAST=$GROUP/last

[ -e $CURRENT ] && desktop=$(ls -1 $CURRENT)
desktop=${desktop:-$(desktop)}

current() {
	if [ -e $CURRENT ] ;then
		[ "$(ls -1 $CURRENT)" = "$(ls -1 $LAST)" ] || { rm -rf $LAST; mv $CURRENT $LAST; }
	else
		mkdir -p $LAST/$desktop
	fi
	mkdir -p $CURRENT/$1
	refresh_panel
	notify Group "$1 $(chef desktop)"
}

plus() {
	tagcount=$(chef desktop count)
	desktop=$(( desktop + $1 ))
	if [ $desktop -gt $tagcount ] ;then
		desktop=1
	elif [ $desktop -lt 1 ] ;then
		desktop=$tagcount
	fi
	echo $desktop
}

msg=$1
case $msg in
	''      ) echo $desktop ;;
	[1-9]   ) desktop focus $1 ;;          # SEE: chef desktop and rulerrc
	-* | +* ) desktop focus $(plus $1) ;;  # -1/+1
	*       )
		shift
		if [ -e $(dirname $0)/functions/desktop/$msg ] ;then
			. $(dirname $0)/functions/desktop/$msg $@
		else
			usage $0 $msg
		fi
esac

# kak: filetype=sh
