#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="is $@" . $PARENT

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# .............................................................. Test operations

# Usage: is <msg> SEE: functions/is

msg=$1
[ $msg ] && shift || usage $0
if [ -e ${0%/is}/functions/is/$msg ] ;then
	. ${0%/is}/functions/is/$msg $@
else
	usage $0 $msg
fi

# kak: filetype=sh
