#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="panel $@" . $PARENT

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................... Draw panel

# Usage: draw <msg>, see functions/panel

DOTDIR=$(dirname $0)/functions/draw
recipe -q panel/format             || exit  # no panel
which lemonbar >/dev/null 2>&1     || exit
pstat "lemonbar -d -n lemonbar:$1" && exit

toggle picom on

# .................................................................. Panel theme

DEFAULT_BG='#00000000'     # alpha channel for panel transparency with picom
DEFAULT_FG="#$(rice color default)"
ACTIVE_FG="#$(rice color active)"
INACTIVE_FG="#$(rice color inactive)"
FREE_FG="#$(rice color free)"
OCCUPIED_FG=$FREE_FG
STARTREK=$(recipe panel/startrek) && ICANDY="#$STARTREK" || ICANDY="$DEFAULT_FG"

transparency() { echo "#$1${2#\#}"; }  # Usage: transparency <amount> #<rrggbb>

# panel font
PANEL_FONT=monograffic  # NOTE: this font does not have NerdFont glyphs (not a pure monospaced font)
PANEL_UNDERLINE=2       # thickness

# panel symbols (tag numbers option dropped to simplify colour assignments)
case $(chef display width) in
	3440 ) TAG_PAD='      '; STATPAD='   ' ;;  # tag bar separator (visual spacing)
	1920 ) TAG_PAD='     ' ; STATPAD='  '  ;;
	*    ) TAG_PAD='    '  ; STATPAD='  '  ;;
esac
[ $(chef display width) -lt 1920 ] && scaledown=true
[ $scaledown ] && { LSEP=${LSEP# }; LSEP=${LSEP% }; RSEP=${RSEP# }; RSEP=${RSEP% }; }

# ..................................................................... Geometry

# Windowchef panel geometry
PANEL_HEIGHT=$(chef screen panel)
PANEL_INDENT=$(chef screen indent)  # assumes equal left/right screen margins

fontsize=$(fontsize)
[ $scaledown ] && fontsize=$(( fontsize - 1 ))
width=$(chef display width)

panel_offsetY=$(( $(chef display height) - PANEL_HEIGHT ))  # bottombar (topbar = 0)
panel_offsetX=$PANEL_INDENT
panel_width=$(( width - PANEL_INDENT * 2 ))

# .................................................................... Tag state

# desktops
tagcount=$(chef desktop count)
DESKTOPS=$(seq 1 $tagcount)

# desktop (group) windows NOTE: -1 is undefined group
for i in -1 $(seq 1 9) ;do mkdir -p $GROUP/$i ;done  # preserve if switching panels within startx session

windows()      { ls -1 $GROUP/$1 | wc -l; }
visible()      { ls -1 $GROUP/$1 | wc -l; }
hidden()       { find $WME -regex "$HIDDEN/.*" | wc -l; }
nilgroup()     { wmctrl -l 2>/dev/null | grep ' -1 ' | wc -l; }
has_windows()  { [ $(windows $1) -gt 0 ]; }
has_visible()  { [ $(visible $1) -gt 0 ]; }
has_hidden()   { [ $(hidden)     -gt 0 ]; }
has_nilgroup() { [ $(nilgroup)   -gt 0 ]; }
deactivated()  { [ -e $GROUP:deactivated/$1 ]; }

# ................................................................... Draw panel

# mkfifo wrapper
mkfifo() { [ -e $1 ] && rm -f $1; mkdir -p ${1%/*}; /bin/mkfifo $1; echo $1; }

handlebar() {
	lemonbar -d -n "lemonbar:$msg" -a 0                             \
		-g ${panel_width}x$PANEL_HEIGHT+$panel_offsetX+$panel_offsetY \
		-u $PANEL_UNDERLINE                                           \
		-f "$PANEL_FONT:size=$fontsize" -F "$DEFAULT_FG" -B "$DEFAULT_BG" 2>/dev/null  # (??) invalid color errors.. from transparency?
}

msg=$1
[ $msg ] && shift || usage: $0
if [ -e ${0%/panel}/functions/panel/$msg ] ;then
	. ${0%/panel}/functions/panel/$msg $@
else
	usage: $0
fi

# kak: filetype=sh
