#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="restore $@" . $PARENT

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................... Restore operations

# Usage: restore <msg> SEE: functions/focus

msg=$1
[ $msg ] && shift || usage $0
if [ -e ${0%/restore}/functions/restore/$msg ] ;then
	. ${0%/restore}/functions/restore/$msg $@
else
	usage $0 $msg
fi

# kak: filetype=sh
