backend = "glx";
vsync = true;
use-damage = true;
xrender-sync-fence = true;
dithered-present = false;

detect-client-opacity = true;

frame-opacity = 1.0;

shadow = false;
fading = false;
corner-radius = 0;
transparent-clipping = false;

inactive-dim-fixed = true;

rules = (
   {
      match = "focused || group_focused";
      dim = 0.0;
   },
   {
      match = "!focused && !group_focused";
      dim = 0.033;
   },
);
