backend = "glx";
vsync = true;
use-damage = true;
xrender-sync-fence = true;
dithered-present = false;

detect-client-opacity = true;

frame-opacity = 1.0;
inactive-opacity = 1.0;
active-opacity = 1.0;

inactive-opacity-override = false;

shadow = false;
fading = false;
corner-radius = 0;
transparent-clipping = false;

focus-exclude = [ ];
opacity-rule = [];

