#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="layout/level $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................ Level windows

for i in $winids ;do
	save_geometry $i            # for full desktop restore :)
	xdotool windowactivate $i
	window snap verticalcenter  # BUG: Super+Shift+g jitter offset occurs when used in a loop
done

xdotool windowactivate $winid

# kak: filetype=sh
