#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# X11 Dynamic Menu
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................... System monitor

alpine || JOURNAL="journal ^$SEP inspect\njournal ^$SEP watch\n"

# meta dmenu menu!
system=$(previous system)
system=$(echo "${JOURNAL}log ^$SEP inspect\nlog ^$SEP watch\nsystem ^$SEP diagnostic" \
	| column -s^ -t | rmenu 'System' "$system" -no-custom) || exit

mhistory system "$system"
case $system in
	journal*inspect   ) exec dmenu journals ;;
	journal*watch     ) exec dmenu journals watch ;;
	log*inspect       ) exec dmenu logs ;;
	log*watch         ) exec dmenu logs watch ;;
	system*diagnostic ) exec dmenu diagnostic ;;
esac

# kak: filetype=sh
