# sdothum - 2016 (c) wtfpl
# Configuration for netmount service

# List of network filesystems
NETWORK_FS="nfs,nfs4,cifs,ceph,glusterfs,fuse.sshfs,davfs"
#NETWORK_FS="nfs4"

# Put here the network manager service name you use
# If you set static ip from rc.local leave commented or empty
#NETWORK_MANAGER=connmand
#NETWORK_MANAGER=NetworkManager

# You can specify your gateway or let it be detected
#GATEWAY=192.168.1.1
GATEWAY=10.1.0.1
