#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="focus/watch" . $PARENT

# herbstluftwm
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................... Watch tag activity

. $HOME/bin/functions/shell/exec_lock

tag=0 
count=0

# trap application closes that bypass herbstluftwm window close
while : ;do
	if [ $tag -eq $(herbstclient attr monitors.focus.tag) ] ;then
		tcount=$(herbstclient attr tags.focus.client_count)
		if [ $count -ne $tcount ] ;then
			[ $count -gt $tcount ] && herbstclient emit_hook focus_window
			count=$tcount 
		fi
	else
		tag=$(herbstclient attr monitors.focus.tag) 
		count=$(herbstclient attr tags.focus.client_count)
	fi
	sleep 1
done &

# vim: set ft=sh: #
