#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... Autostart

# see .xinitrc for 2bwm autostart hack :)

restore root
conky clock auto
draw panel
restore unclutter
pulse
udev
qk stop  # HACK: need to start in a term session
desktop 0

# kak: filetype=sh
