#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="draw $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .............................................................. Draw operations

# Usage: draw <msg>, see functions/draw

msg=$1
[ $msg ] && shift || usage: $0
if [ -e $(dirname $0)/functions/draw/$msg ] ;then
	. $(dirname $0)/functions/draw/$msg $@
else
	usage: $0
fi

# vim: set ft=sh: #
