#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="focus $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................. Focus operations

# Usage: focus <msg>, see functions/focus

msg=$1
[ $msg ] && shift || usage: $0
if [ -e ${0%/focus}/functions/focus/$msg ] ;then
	. ${0%/focus}/functions/focus/$msg $@
else
	usage: $0
fi

# vim: set ft=sh: #
