#!/usr/bin/dash
# sdothub - 2016 (c) wtfpl
[ $TRACE ] && CHILD="config/appbinds $@" . $PARENT

# herbstluftwm
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................ Applications keybinds

# commented (out) actions are historical references
# infrequent dmenu functions may be referenced with Super-F1

hc keybind Super-Shift-space        spawn dmenu run
# hc keybind Super-Shift-space      spawn dmenu apps
# hc keybind Super-Shift-space      spawn dmenu manpages
hc keybind Super-Alt-Shift-space    spawn killall -KILL dmenu
hc keybind Control-space            spawn dunstctl close
hc keybind Control-Shift-space      spawn dunstctl close-all
hc keybind Control-BackSpace        spawn dunstctl history-pop
# hc keybind Super-1                spawn pactl set-sink-volume $(sink) -3db
# hc keybind Super-2                spawn pactl set-sink-volume $(sink) 0db
# hc keybind Super-3                spawn pactl set-sink-volume $(sink) +3db
# hc keybind Super-0                spawn pactl set-sink-mute $(sink) toggle
# hc keybind Super-Alt-0            spawn toggle pavucontrol
# hc keybind Super-4                spawn sudo xbacklight -5
# hc keybind Super-5                spawn sudo xbacklight =100
# hc keybind Super-6                spawn sudo xbacklight +5
# hc keybind Super-equal            spawn dmenu calc
# hc keybind Super-Control-equal    spawn toggle plover
hc keybind Super-apostrophe         spawn dmenu pass
hc keybind Super-Shift-apostrophe   spawn toggle panel
# hc keybind Super-Alt-apostrophe   spawn toggle conky
# hc keybind Super-F1               spawn keymap toggle
hc keybind Super-F1                 spawn dmenu menu
hc keybind Super-a                  spawn toggle scratchpad mail aerc
hc keybind Super-Shift-a            spawn dmenu abook
# hc keybind Super-Control-a        spawn dmenu notes draft
hc keybind Super-b                  spawn focus $BROWSER
# hc keybind Super-Control-b        spawn bookmark
# hc keybind Super-Alt-Control-b    spawn dmenu history
# hc keybind Super-Alt-b            chain . spawn pkill -KILL $BROWSER . emit_hook focus_window
hc keybind Super-Alt-b              chain . spawn qutebrowser closeall . emit_hook focus_window
# hc keybind Super-Shift-b          spawn dmenu bookmarks
# hc keybind Super-Control-c        spawn term 'todo' td -i
# hc keybind Super-d                spawn dmenu dict
# hc keybind Super-Control-d        spawn dmenu thesaurus
hc keybind Super-e                  spawn dmenu scripts
hc keybind Super-Shift-e            spawn dmenu projects
hc keybind Super-Control-e          spawn dmenu edit
# hc keybind Super-Alt-e            spawn hardcopy eject
# hc keybind Super-Alt-Control-e    spawn proof toggle
# hc keybind Super-h                spawn hangouts
# hc keybind Super-Control-h        spawn dmenu shistory
# hc keybind Super-Control-k        spawn clack toggle
# hc keybind Super-Alt-k            spawn clack swap
# hc keybind Super-l                spawn lock_screen
# hc keybind Super-Alt-p            spawn pulse restart
hc keybind Super-Control-q          spawn dmenu halt
# hc keybind Super-r                spawn dmenu clipboard
# hc keybind Super-s                spawn dmenu systemd
hc keybind Super-s                  spawn dmenu system
hc keybind Super-t                  spawn conky clock
hc keybind Super-Control-t          spawn qclocktwo
hc keybind Super-Shift-t            spawn dmenu reminder
# hc keybind Super-Alt-t            spawn dmenu alarm
hc keybind Super-u                  spawn dmenu notes
hc keybind Super-Shift-u            spawn dmenu notes supernote
hc keybind Super-Control-u          spawn dmenu notes poem
hc keybind Super-v                  spawn dmenu media
hc keybind Super-Shift-v            spawn dmenu audio
hc keybind Super-Alt-v              chain . spawn pkill '(mpv|omxplayer)' . emit_hook focus_window
hc keybind Super-Shift-w            spawn weather time
hc keybind Super-x                  spawn toggle nnn TMUX
hc keybind Super-Shift-x            spawn toggle pcmanfm
hc keybind Super-y                  spawn dmenu wiki
hc keybind Super-Shift-y            spawn dmenu wiki diary
# hc keybind Super-z                spawn toggle rox
# hc keybind Super-Control-z        spawn dmenu screensaver

# vim: set ft=sh: #
