#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................................ Files

# Usage: menu logs [watch]

# view log files
[ $1 ] && mode=Watch || mode=View
cd /tmp
ln_logs

file=$(previous logs)
file=$(ls *.log | sort | sed 's/.log//' | rmenu "$mode Log" $file -no-custom) || exit

mhistory logs $file
case $mode in
	View  ) [ $file ] && term "$file" less $file.log ;;
	Watch ) [ $file ] && term "$file" tail -f $file.log ;;
esac

# kak: filetype=sh
