#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................ Edit projects

# Format: <tag> :: [ <filename> | $(<eval>) ]*
#               where, tag      - menu search tag
#                      filename - posix filename expression
#                      eval     - posix shell expression that evaluates to a list of *non-blank* filenames

EDIT='edit tags'

EDITOR=${EDITOR:-helix}

# tag file containing project specs
PROJECTS=$MENU/.projectsrc
history=$HISTORY/projects

projects() { sed "s/  *::  */^$SEP /" $PROJECTS | mhistory projects | column -s^ -t | sed "2i$(X $EDIT)"; }

while files=$(projects | rmenu 'Edit Project' -no-custom) || exit ;do
	case ${files#$(X)} in
		"$EDIT" ) $EDITOR WAIT $PROJECTS $history ;;
	
		*       )
			mhistory projects "$(echo $files | sed "s/ *$SEP/^$SEP/")"
			eval echo ${files#*$SEP} | tr ' ' '\n' | exclude | sort | xargs -r $EDITOR
			break ;;  # required to prevent duplicate eval execution
	esac
done

# vim: set ft=sh: #
