#!/usr/bin/dash
#
# sdothum - 2016 (c) wtfpl

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................. Window size

actions() {
	echo "Mod+Ctrl+w   size
Mod+0        revert
Mod+1        rotate
Mod+2        monocle
  p          top
  b          bottom
  f          left
  g          right
  3          top left
  4          top right
  5          bottom left
  6          bottom right
  j          vertical left
  k          vertical right
Mod+8        1/4 screen left
Mod+7        1/4 screen right
  y          1/3 screen left
  x          1/3 screen right
  :          1/3 screen center"
}

# keybinds to menu windowstretch not currently assigned in 2bwm SEE: menu windowsize
[ $1 ] && cmd=$(actions | grep "Mod[+]$1 ") || cmd=$(actions | rmenu 'Stretch window to' $cmd -no-custom) || exit

cmd=$(echo "$cmd" | sed "s/^[^ ]* *//")
case $cmd in
	size       ) menu windowsize            ;;
	revert     ) window revert              ;;
	rotate     ) window rotate              ;;
	monocle    ) window size monocle        ;;
	top        ) window stretch top         ;;
	bottom     ) window stretch bottom      ;;
	left       ) window stretch left        ;;
	right      ) window stretch right       ;;
	t*left     ) window stretch topleft     ;;
	t*right    ) window stretch topright    ;;
	b*left     ) window stretch bottomleft  ;;
	b*right    ) window stretch bottomright ;;
	v*left     ) window stretch fullleft    ;;
	v*right    ) window stretch fullright   ;;
	1/4*left   ) window stretch 4 left      ;;
	1/4*right  ) window stretch 4 right     ;;
	1/3*left   ) window stretch 3 left      ;;
	1/3*center ) window stretch 3 center    ;;
	1/3*right  ) window stretch 3 right     ;;
	near*      ) window stretch near        ;; # horizontal axis
	far*       ) window stretch far         ;;
esac

# kak: filetype=sh
