---
services: 
 nicotineplus-proper:
   image: 'sirjmann92/nicotineplus-proper:latest' # Or pull from GitHub: 'ghcr.io/sirjmann92/nicotineplus-proper:latest'
   container_name: nicotine
#  network_mode: "container:YourVPNContainerNameHere" # Comment this line out if you're NOT using a VPN container
   ports: # Comment this line out if you ARE using a VPN container (line above)
     - '6565:6565' # Comment this line out if you ARE using a VPN container (lines above)
     - '2234:2234' # Comment this line out if you ARE using a VPN container (lines above)
#  env_file: .env # Optionally use a .env file to store environment variables and login credentials
   environment: # All environment variables are optional, defaults are listed (TZ, LANG, UMASK, and FORWARD_PORT have no default)
     - TZ=America/Toronto
     - LOGIN=sdothum
     - PASSW=TMRH11rNSvmM
     - PUID=1000
     - PGID=1000
     - DARKMODE=False
     - LANG=en_US.UTF-8
  #   - UMASK=022
  #   - UPNP=False 
  #   - AUTO_CONNECT=True
  #   - TRAY_ICON=False
  #   - NOTIFY_FILE=False
  #   - NOTIFY_FOLDER=False
  #   - NOTIFY_TITLE=False
  #   - NOTIFY_PM=False
  #   - NOTIFY_CHATROOM=False
  #   - NOTIFY_MENTION=False
  #   - FORWARD_PORT=12345 # Useful for dynamic port forwarding
  #   - WEB_UI_PORT=6565 # for custom webUI port assignment. Should match 'port' env variable or VPN webUI port
  #   - WEB_UI_USER=YourWebUIUsername # for custom webUI basic auth username
  #   - WEB_UI_PASSWORD=YourWebUIPassword # for custom webUI basic auth password
   volumes:
     - /net/downloads/nicotine:/downloads
     - /home/music:/music
     - /home/library/calibre:/calibre
     - /home/shum/.config/nicotine:/config # Save your config persistently
     - /home/shum/.local/share/nicotine:/data # Store your logs, database, and history
   restart: unless-stopped

