#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="window/toggle $@" . $PARENT

# Faouzia
# ══════════════════════════════════════════════════════════════════════════════

# ..................................................... Toggle window visibility
set -x
# Usage: toggle [--name] <name>

case $1 in
	--name ) option=--name; name=$2 ;;
	*      ) name=$1 ;;
esac

map() {
	[ -n "$1" ] && sirocco window hide $1 && exit 0
	return 1
}

unmap() {
	[ -n "$1" ] && sirocco window focus $1 && exit 0
	return 1
}

# SEE: sxhkdrc
map $(nimctlr window ids $option $name) || unmap $(nimctlr window ids --all $option $name)

exit 1

# kak: filetype=sh
