#!/bin/sh
# sdothum - 2016 (c) wtfpl

# server=google.com
server=0.ca.pool.ntp.org
interface=wlp9s0
latency=100  # minimum acceptable (ms)

timestamp() { date "+%y-%m-%d %H:%M:%S│  $@"; }

resusitate() {
	sudo ifconfig $interface down
	sudo ifconfig $interface up
	timestamp "interface: down.. up⠁⠁⠁"
	# speedtest --progress=no | tr -d '\r'  # clean up '^M' from log
}

heartbeat() {
	while : ;do
		speed=$(ping -c1 $server 2>/dev/null | grep 'time=' | sed -r 's/.*time=([0-9]*).*/\1/')
		[ ${speed:-${latency}0} -gt $latency ] && resusitate
		sleep 10
	done &
}

case $1 in
	''   )
		timestamp "starting on $interface: $server"
		for i in $(seq 1 100) ;do
			ping -c1 $server >/dev/null 2>&1 && { heartbeat; exit 0; }
			sleep 0.1
		done
		exit 1
		;;
	stop )
		sudo pkill ifconfig  # kill any resusitate..
		pkill -f speedtest
		pkill -f "ping .*$server"
		exit 0
		;;
esac

# kak: filetype=sh
