#!/bin/sh
# sdothum - 2016 (c) wtfpl

MAILDIR=$HOME/Mail
LOCK=$MAILDIR/.notmuch/xapian/flintlock
ACCT=$(grep 'Inbox' $HOME/.mbsyncrc | cut -d/ -f3)
MAILBOX=$MAILDIR/$ACCT
[ -e $MAILBOX ] || mkdir -p $MAILBOX  # mbsync requires existence of mail account folder

STATE=$HOME/.local/state/dinit.d/mbsync
[ -e $STATE ] || mkdir -p $STATE
NOTMUCH=$STATE/notmuch
IMAGE=$STATE/image
SNAPSHOT=$STATE/snapshot
[ -e $SNAPSHOT ] || touch $SNAPSHOT

curl -u ${ACCT}:$(cat $MAILDIR/.mailsync) --silent 'https://mail.google.com/mail/feed/atom' \
	| perl -ne 'print '\t' if /<name>/; print "$2\n" if /<(title|name)>(.*)<\/\1>/ ;' >$IMAGE
cmp -s $SNAPSHOT $IMAGE && exit 0  # no new mail
mv -f $IMAGE $SNAPSHOT

date '+%Y-%m-%d %H:%M:%S mbsync'
find $MAILBOX -type f -size 0 -not -name "${LOCK##*/}" -exec rm -fv {} \;  # purge empty messages
# mbsync -a --verbose >>/tmp/mbsync.log 2>&1
mbsync -Dmn $ACCT >/dev/null 2>&1

[ -e $LOCK ] && rm $LOCK
notmuch new >$NOTMUCH 2>&1
tail -1 $NOTMUCH | grep -q 'No new mail.' ||  date '+%Y-%m-%d %H:%M:%S ......notmuch'

exit 0

# kak: filetype=sh
