#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# Faouzia
# ══════════════════════════════════════════════════════════════════════════════

# Usage: faouziarc refresh SEE: gaps

# ...................................................................... Borders

sirocco wm_config enable_borders           $(recipe -c ui/enable_borders true)
sirocco wm_config border_width             $(recipe -c ui/border_width 6)
sirocco wm_config internal_border_width    $(recipe -c ui/internal_border_width 4)
sirocco wm_config border_style             $(recipe -c ui/border_style 1)
sirocco wm_config corner_percent           $(recipe -c ui/corner_percent 20)
sirocco wm_config corner_mask              $(recipe -c ui/corner_mask 8)

sirocco wm_config color_focused            0x$(recipe -c ui/color_focused ffff0000)
sirocco wm_config color_unfocused          0x$(recipe -c ui/color_unfocused 00000000)
sirocco wm_config internal_color_focused   0x$(recipe -c ui/internal_color_focused 00000000)
sirocco wm_config internal_color_unfocused 0x$(recipe -c ui/internal_color_unfocused $(recipe ui/internal_color_focused))

# ......................................................................... Gaps

sirocco wm_config gap_width top    $(recipe -c 'ui/gap_width top' 45)
sirocco wm_config gap_width bottom $(recipe -c 'ui/gap_width bottom' 45)
sirocco wm_config gap_width left   $(recipe -c 'ui/gap_width left' 58)
sirocco wm_config gap_width right  $(recipe -c 'ui/gap_width right' $(recipe 'ui/gap_width left'))
sirocco wm_config grid_gap_width   $(recipe -c ui/grid_gap_width 33)

[ $1 ] && exit

# ....................................................................... Groups

sirocco wm_config groups_nr      10  # SEE: group (action) and rulerrc for group labels
sirocco wm_config sticky_windows false

# .................................................................... Behaviour

sirocco wm_config cursor_position             center
sirocco wm_config enable_resize_hints         true
sirocco wm_config enable_sloppy_focus         true
sirocco wm_config enable_last_window_focusing true
sirocco wm_config apply_settings              true

# ........................................................................ Mouse

sirocco wm_config replay_click_on_focus true
sirocco wm_config pointer_actions       move resize_side resize_corner
sirocco wm_config pointer_modifier      super
sirocco wm_config click_to_focus        any

# ................................................................... State tree

mkdir -p $SNAPSHOT
mkdir -p $GROUP/-1
mkdir -p $GROUP/current/1
mkdir -p $GROUP/last/-1
mkdir -p $GROUP:deactivated
mkdir -p $HIDDEN
mkdir -p $WINFO:snapshot

# allow pseudo (file) writes to yet as undefined $FIFO/<fifo> buffer during startup SEE: panel
mkdir -p $FIFO

# ...................................................................... Startup

recipe -d pfw  # pfw wrapper winid mismatch stats

autostart

# state tree check NOTE: also triggers panel/desktop update
while : ;do
	# NIMCTLR_TRACE=1 nimctlr sync window
	$NIMCTLR sync window
	sleep 1
done

# kak: filetype=sh
