#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="window $@" . $PARENT

# Faouzia
# ══════════════════════════════════════════════════════════════════════════════

# .............................................................. Desktop layouts

# Usage: layout <msg> SEE: functions/layout

winid=$(pfw)

msg=$1
[ $msg ] && shift || usage $0
if [ -e ${0%/layout}/functions/layout/$msg ] ;then
	. ${0%/layout}/functions/layout/$msg $@
else
	usage $0 $msg
fi

# kak: filetype=sh
