#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="toggle $@" . $PARENT

# Faouzia
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................ Toggle operations

# Usage: toggle [<msg>] SEE: functions/toggle

msg=$1
[ $msg ] && shift || usage $0
if [ -e ${0%/toggle}/functions/toggle/$msg ] ;then
	. ${0%/toggle}/functions/toggle/$msg $@
elif [ $(nimctlr window count --all "$1") -gt 0 ] ;then
	winid=$(sirocco window ids "$msg" | head -1)
	[ -n "$winid" ] && sirocco window hide "$winid" || sirocco window focus $(sirocco window ids --all "$msg" | head -1)
else
	$@
fi

# kak: filetype=sh
