MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
# COMMAND_ENABLE = no
NKRO_ENABLE = yes
# STENO_LAYERS = no
STENO_ENABLE = no
# VIRTSER_ENABLE = yes
AUDIO_ENABLE = no
MIDI_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
LTO_ENABLE = yes


# TMPVAR := $(SRC)
# SRC = $(filter-out sten.c, $(TMPVAR))
