#!/bin/bash

# berryc focus_color         "00ffff"
# berryc unfocus_color       "757575"
# berryc inner_focus_color   "505050"
# berryc inner_unfocus_color "505050"
# berryc text_focus_color    "ffffff"
# berryc text_unfocus_color  "ffffff"
# berryc set_font            "adrift-9"
berryc border_width        12
berryc inner_border_width  10
berryc title_height        12
berryc top_gap             0
berryc edge_gap            37 37 42 42
berryc draw_text           "false"
berryc smart_place         "true"
berryc json_status         "true"
berryc decorate_new        "true"
berryc edge_lock           "true"
# berryc pointer_interval    0
# berryc save_monitor        1 1
# berryc name_desktop        "ONE"
# berryc manage              "Dialog|Toolbar|Menu|Splash|Utility"
# berryc unmanage            "Dialog|Toolbar|Menu|Splash|Utility"


# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
# berryc smart_place "true"
# berryc draw_text   "true"
# berryc edge_lock   "true"
# berryc set_font    "Dina-9"
