#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="restore $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................... Restore operations

# Usage: restore <msg>, see functions/focus

msg=$1
[ $msg ] && shift || usage: $0
if [ -e ${0%/restore}/functions/restore/$msg ] ;then
	. ${0%/restore}/functions/restore/$msg $@
else
	usage: $0
fi

# kak: filetype=sh
