#!/bin/sh
# sdothum - 2016 (c) wtfpl

MAILDIR=$HOME/Mail
ACCT=$(grep 'Inbox' $HOME/.mbsyncrc | cut -d/ -f3)
MAILBOX=$MAILDIR/$ACCT
[ -e $MAILBOX ] || mkdir -p $MAILBOX  # mbsync requires existence of mail account folder

STATE=$HOME/.local/state/dinit.d/mbsync
[ -e $STATE ] || mkdir -p $STATE
NOTMUCH=$STATE/notmuch
NEW=$STATE/new
OLD=$STATE/old
[ -e $OLD ] || touch $OLD

curl -u ${ACCT}:$(cat $MAILDIR/.mailsync) --silent 'https://mail.google.com/mail/feed/atom' \
	| perl -ne 'print '\t' if /<name>/; print "$2\n" if /<(title|name)>(.*)<\/\1>/ ;' >$NEW
cmp -s $OLD $NEW && exit 0  # no new mail
mv $NEW $OLD

date '+%Y-%m-%d %H:%M:%S mbsync'
rm -f $MAILDIR/.notmuch/xapian/flintlock >/dev/null 2>&1
find $MAILBOX -type f -size 0 -exec rm -fv {} \;  # purge empty messages
# mbsync -a --verbose >>/tmp/mbsync.log 2>&1
mbsync -Dmn $ACCT >/dev/null 2>&1

notmuch new >$NOTMUCH 2>&1
tail -1 $NOTMUCH | grep -q 'No new mail.' ||  date '+%Y-%m-%d %H:%M:%S notmuch'

exit 0

# kak: filetype=sh
