#!/bin/sh
# sdothum - 2016 (c) wtfpl

cd /home/shum/docker/sirjmann92:nicotineplus-proper

case $1 in
	''   )
		while : ;do
			ping -c1 server.slsknet.org >/dev/null 2>&1 && break
			sleep 1
		done
		docker compose up  # NOTE: init launch oft cycles server reconnects SEE: windowchef autostart
		;;
	stop )
		docker compose stop
		;;
esac

# kak: filetype=sh
