#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... Autostart

restore root
restore panel
conky clock auto
restore unclutter
pulse
udev
qk stop  # HACK: need to start in a term session
brightness
[ -e $SESSION/cbonsai ] && cbonsai
[ -e $SESSION/term    ] && term

# issue running as runit service
!p nzbget && nzbget --daemon
!p sonarr && sudo /bin/su - sonarr -c '/usr/lib/sonarr/Sonarr/Sonarr -s localhost:8989 -no-browser -data=/var/lib/sonarr' >/dev/null 2>&1 &

# kak: filetype=sh
