#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... Autostart

restore root
restore panel
conky clock auto
restore unclutter
pulse
udev
qk stop  # HACK: need to start in a term session
brightness
[ -e $SESSION/cbonsai ] && cbonsai
[ -e $SESSION/term    ] && term

# kak: filetype=sh
