#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... Autostart

# see .xinitrc for 2bwm autostart hack :)

xdotool set_desktop 0  # for window hide/unhide BECAUSE: windowchef does not define any desktops

restore root
conky clock auto
draw panel
restore unclutter
pulse
udev
qk stop  # HACK: need to start in a term session

# kak: filetype=sh
