#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="chef $@" . $PARENT

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# .......................................................... Windowchef metadata

# Usage: chef <msg> SEE: functions/chef

msg=$1
[ $msg ] && shift || usage $0
if [ -e ${0%/chef}/functions/chef/$msg ] ;then
	. ${0%/chef}/functions/chef/$msg $@
else
	usage $0 $msg
fi

# kak: filetype=sh
