#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="desktop $@" . $PARENT

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................. Group operations

# Usage: desktop <msg>
#          where <msg>: <group> [specific | toggle | close]
#                       last

[ -e $WME:desktop ] && desktop=$(cat $WME:desktop)
desktop=${desktop:--1}  # desktops in windowchef are groups!

current() {
	if [ -e $WME:desktop ] ;then
		if [ -e $WME:desktop:last ] ;then
			cmp --silent $WME:desktop  $WME:desktop:last && mv $WME:desktop $WME:desktop:last
		fi
	else
		echo $desktop >$WME:desktop:last
	fi
	echo $1 >$WME:desktop
	notify Group "$1 $(chef desktop)"
}

toggle() {
	if [ -e $WME:group:$1:deactivated ] ;then
		waitron group_activate $1
		waitron window_focus $(window stack $1)
		rm $WME:group:$1:deactivated
		desktop $1
	else
		winid=$(cat $WME:group:$1 | head -1 2>/dev/null)
		[ $winid ] || return
		waitron window_focus $winid  # BUG: waitron group_toggle/_deactivate does not deactivate whole group unless the top of the window stack has focus
		waitron group_deactivate $1
		touch $WME:group:$1:deactivated
	fi
}

desktop() {
	case $2 in
		specific )
			[ $desktop -eq $1 ] || current $1
			waitron group_activate_specific $1
			;;
		toggle   )
			[ $desktop -eq $1 ] || current $1
			toggle $1
			;;
		close    )
			for i in $(cat $WME:group:$1) ;do
				waitron window_focus $i
				waitron window_close
			done
			waitron group_remove_all_windows $1  # redundancy trap for unknown group juggling corner cases
			>$WME:group:$1
			rm $WME:group:$1:focus
			;;
		*        )
			echo $(pfw) >$WME:group:$1:focus                 # see window stack
			[ $desktop -eq $1 ] && return
			current $1
			waitron group_activate $1
			waitron window_focus $(cat $WME:group:$1:focus)  # restore window stack NOTE: this also fixes calibre mouse focus issue!
			;;
	esac
}

plus() {
	desktop=$(( $desktop + $1 ))
	if [ $desktop -gt 6 ] ;then
		desktop=1
	elif [ $desktop -lt 1 ] ;then
		desktop=6
	fi
	echo $desktop
}

case $1 in
	''    ) echo $desktop ;;
	[1-9] ) desktop $1 $2 ;;       # SEE: chef desktop and rulerrc
	last  ) [ -e $WME:desktop:last ] && desktop $(cat $WME:desktop:last) ;;
	*     ) desktop $(plus $1) ;;	 # -1/+1
esac

# kak: filetype=sh
