#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="draw $@" . $PARENT

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# .............................................................. Draw operations

# Usage: draw <msg>, see functions/draw

msg=$1
[ $msg ] && shift || usage: $0
if [ -e ${0%/draw}/functions/draw/$msg ] ;then
	. ${0%/draw}/functions/draw/$msg $@
else
	usage: $0
fi

# kak: filetype=sh
