#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="is $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .............................................................. Test operations

# Usage: is <msg>, see functions/is

msg=$1
[ $msg ] && shift || usage: $0
if [ -e ${0%/is}/functions/is/$msg ] ;then
	. ${0%/is}/functions/is/$msg $@
else
	usage: $0
fi

# kak: filetype=sh
