#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="rice $@" . $PARENT

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................... Rice utilities

# Usage: rice [<msg>] SEE: functions/rice

msg=$1
[ $msg ] && shift || usage $0
if [ -e $(dirname $0)/functions/rice/$msg ] ;then
	. $(dirname $0)/functions/rice/$msg $@
else
	usage $0 $msg
fi

# kak: filetype=sh
