#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl

# Windowchef
# ══════════════════════════════════════════════════════════════════════════════

# ...................................................................... Borders

waitron wm_config enable_borders true
waitron wm_config border_width 12
waitron wm_config internal_border_width 10
waitron wm_config color_focused 0x00ffff
waitron wm_config color_unfocused 0x757575
waitron wm_config internal_color_focused 0x505050
waitron wm_config internal_color_unfocused 0x505050

	# ...................................................................... Gaps

waitron wm_config gap_width all 37
waitron wm_config grid_gap_width 10

# ....................................................................... Groups

waitron wm_config groups_nr 10
waitron wm_config sticky_windows true

# .................................................................... Behaviour

waitron wm_config cursor_position center
waitron wm_config enable_resize_hints false
waitron wm_config enable_sloppy_focus true
waitron wm_config enable_last_window_focusing true
waitron wm_config apply_settings true

# ........................................................................ Mouse

waitron wm_config replay_click_on_focus true
waitron wm_config pointer_actions move resize_side resize_corner
waitron wm_config pointer_modifier super
waitron wm_config click_to_focus any
