#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="window/revert $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ....................................................... Revert window geometry

# Usage: window revert [winid]

# SEE: window size,  stretch and snap
[ -e $WINFO:${1:-$winid} ] && eval $(cat $WINFO:${1:-$winid}) || exit
draw ${1:-$winid} $WIDTH $HEIGHT
xdotool windowmove ${1:-$winid} $X $Y

# kak: filetype=sh
