#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="window/snap $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................. Snap windows

# Usage: window snap [left | center | right | up | down | all (windows on desktop)]

set_geometry     # X Y WIDTH HEIGHT
# save_geometry  # do not overwrite window sizing/tiling save_geometry

# .................................................................... Snap left

left() {
	xdotool windowmove $winid $(( $margin + $border - 1 )) y
	xdotool windowactivate $winid
}

# .................................................................... Snap left

centerleft() {
	xdotool windowmove $winid $(( $width / 2 + $margin - $WIDTH - $border * 2 )) y
	xdotool windowactivate $winid
}

# .................................................................... Snap left

centerright() {
	xdotool windowmove $winid $(( $width / 2 + $margin )) y
	xdotool windowactivate $winid
}

# ................................................................... Snap right

right() {
	xdotool windowmove $winid $(( $width - $WIDTH + $border * 2 - 1 )) y
	xdotool windowactivate $winid
}

# .................................................................... Snap near

near() {
	[ $X -le $(opposite_side) ] && left || right
	xdotool windowactivate $winid
}

# ...................................................................... Snap up

up() {
	xdotool windowmove $winid x $margin
	xdotool windowactivate $winid
}

# .................................................................... Snap down

down() {
	# xdotool windowmove $winid x $(( $height - $HEIGHT - $margin - $border * 2 ))
	xdotool windowmove $winid x $(( $height - $HEIGHT ))
	xdotool windowactivate $winid
}

# ......................................................... Snap vertical center

verticalcenter() {
	xdotool windowmove $winid x $(( ($height - $HEIGHT) / 2 + $panel - $border ))
	xdotool windowactivate $winid
}

case $1 in
	''       ) near            ;; # nearest left/right edge
	left     ) left            ;;
	c*left   ) centerleft      ;;
	center   ) xdotool key Super+g ;;
	c*right  ) centerright     ;;
	right    ) right           ;;
	up       ) up              ;;
	down     ) down            ;;
	v*center ) verticalcenter  ;;
esac

# kak: filetype=sh
