#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="window/snap $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................. Snap windows

# Usage: window snap [left | center | right | top | bottom | all (windows on desktop)]

set_geometry  # X Y WIDTH HEIGHT
save_geometry

# .................................................................... Snap left

left() {
	xdotool windowmove $winid $(( $margin + $border - 1 )) y
	xdotool windowactivate $winid
}

# .................................................................... Snap left

centerleft() {
	xdotool windowmove $winid $(( $width / 2 + $margin - $WIDTH - $border * 2 )) y
	xdotool windowactivate $winid
}

# .................................................................... Snap left

centerright() {
	xdotool windowmove $winid $(( $width / 2 + $margin )) y
	xdotool windowactivate $winid
}

# ................................................................... Snap right

right() {
	xdotool windowmove $winid $(( $width - $WIDTH + $border * 2 - 1 )) y
	xdotool windowactivate $winid
}

# .................................................................... Snap near

near() {
	[ $X -le $(opposite_side) ] && left || right
	xdotool windowactivate $winid
}

# ..................................................................... Snap top

top() {
	xdotool windowmove $winid x $margin
	xdotool windowactivate $winid
}

# .................................................................. Snap bottom

bottom() {
	# xdotool windowmove $winid x $(( $height - $HEIGHT - $margin - $border * 2 ))
	xdotool windowmove $winid x $(( $height - $HEIGHT ))
	xdotool windowactivate $winid
}

# .................................................... Snap all windows to level

horizon() {
	desktop=$(xdotool get_desktop)
	winids=$(wmctrl -l | grep "^[^ ]*  *$desktop " | cut -d' ' -f1)  # of current desktop

	for i in $winids ;do
		# xdotool windowactivate $i
		xdotool windowactivate $i  # faster
		save_geometry $i           # for full desktop restore :)
		xdotool key Super+Shift+g  # 2bwm vertical center
	done

	xdotool windowactivate $winid
}

# .......................................................... Restore all windows

restore() {
	desktop=$(xdotool get_desktop)
	winids=$(wmctrl -l | grep "^[^ ]*  *$desktop " | cut -d' ' -f1)  # of current desktop

	for i in $winids ;do
		window revert $i
	done

	xdotool windowactivate $winid
}

case $1 in
	''      ) near            ;; # nearest left/right edge
	left    ) left            ;;
	c*left  ) centerleft      ;;
	center  ) xdotool key Super+g ;;
	c*right ) centerright     ;;
	right   ) right           ;;
	top     ) top             ;;
	bottom  ) bottom          ;;
	all     ) horizon         ;;
	restore ) restore         ;;
esac

# kak: filetype=sh
