#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="window/stretch $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .............................................................. Stretch windows

# Usage: window stretch [[top | bottom | full] [left | right] | near | far]

set_geometry  # X Y WIDTH HEIGHT

# .................................................................. Stretch top

top() {
	height=$(( $Y + $HEIGHT - $panel ))
	draw $winid $WIDTH $height
	xdotool windowmove $winid $X $panel
	xdotool windowactivate --sync $winid
}

# ............................................................... Stretch bottom

bottom() {
	height=$(( $height - $Y + $border ))
	draw $winid $WIDTH $height
	xdotool windowmove $winid $X $Y
	xdotool windowactivate --sync $winid
}

# ................................................................. Stretch left

left() {
	width=$(( $X + $WIDTH - $margin ))
	draw $winid $width $HEIGHT
	xdotool windowmove $winid $margin $Y
	xdotool windowactivate --sync $winid
}

# ................................................................ Stretch right

right() {
	width=$(( $width - $X + $margin ))
	draw $winid $width $HEIGHT
	xdotool windowmove $winid $X $Y
	xdotool windowactivate --sync $winid
}

# ............................................................. Stretch top left

topleft() {
	height=$(( $Y + $HEIGHT - $panel ))
	width=$(( $X + $WIDTH - $margin ))
	draw $winid $width $height
	xdotool windowmove $winid $margin $panel
	xdotool windowactivate --sync $winid
}

# ............................................................ Stretch top right

topright() {
	height=$(( $Y + $HEIGHT - $panel ))
	width=$(( $width - $X + $margin ))
	draw $winid $width $height
	xdotool windowmove $winid $X $panel
	xdotool windowactivate --sync $winid
}

# .......................................................... Stretch bottom left

bottomleft() {
	height=$(( $height - $Y + $border ))
	width=$(( $X + $WIDTH - $margin ))
	draw $winid $width $height
	xdotool windowmove $winid $margin $Y
	xdotool windowactivate --sync $winid
}

# ......................................................... Stretch bottom right

bottomright() {
	height=$(( $height - $Y + $border ))
	width=$(( $width - $X + $margin ))
	draw $winid $width $height
	xdotool windowmove $winid $X $Y
	xdotool windowactivate --sync $winid
}

# ..................................................... Stretch full screen left

fullleft() {
	height=$(( $height - $border * 2 ))
	width=$(( $X + $WIDTH - $margin ))
	draw $winid $width $height
	xdotool windowmove $winid $margin $panel
	xdotool windowactivate --sync $winid
}

# .................................................... Stretch full screen right

fullright() {
	height=$(( $height - $border * 2 ))
	width=$(( $width - $X + $margin ))
	draw $winid $width $height
	xdotool windowmove $winid $X $panel
	xdotool windowactivate --sync $winid
}

# ................................................................. Stretch near

near() {
	[ $X -le $(opposite_side) ] && left || right
	xdotool windowactivate --sync $winid
}

# .................................................................. Stretch far

far() {
	[ $X -le $(opposite_side) ] && right || left
	xdotool windowactivate --sync $winid
}

case $1 in
	''      ) near        ;;
	top     ) top         ;;
	bottom  ) bottom      ;;
	left    ) left        ;;
	right   ) right       ;;
	t*left  ) topleft     ;;
	t*right ) topright    ;;
	b*left  ) bottomleft  ;;
	b*right ) bottomright ;;
	f*left  ) fullleft    ;;
	f*right ) fullright   ;;
	near    ) near        ;;  # horizontal axis
	far     ) far         ;;
esac

# kak: filetype=sh
