#!/bin/sh
# sdothum - 2016 (c) wtfpl

export CONTENT_SECURITY_POLICY="default-src 'self'; font-src 'self'; style-src 'self' 'unsafe-inline';"

/usr/bin/miniflux.app -c /etc/miniflux.conf

# kak: filetype=sh
