#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="query/display $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................... Display resolution

# Usage: query display [height | width]

# replaced by wmutils
# display() { xrandr | grep -w connected | sed -r 's/.* ([0-9]*x[0-9]*\+[0-9]\+*[0-9]*) .*/\1/' | awk -F'[ +x]' '{ print $1,$2 }'; }

case $1 in
	height ) wattr h $(lsw -r) ;;  # display | cut -d' ' -f2 ;;
	width  ) wattr w $(lsw -r) ;;  # display | cut -d' ' -f1 ;;
	*      ) echo "$(wattr w $(lsw -r)) $(wattr h $(lsw -r))" ;;  # typically, set -- $(query display) to reference X Y as $1 $2
esac

# kak: filetype=sh
