#!/bin/sh
# sdothum - 2016 (c) wtfpl

# export CONTENT_SECURITY_POLICY="default-src 'self'; font-src 'self'; style-src 'self' 'unsafe-inline';"
# export LISTEN_ADDR=0.0.0.0:8080
export BASE_URL=http://10.1.0.11

/usr/bin/miniflux.app -c /etc/miniflux.conf

# kak: filetype=sh

