#!/bin/sh
# sdothum - 2016 (c) wtfpl

cd /home/shum/docker/sirjmann92:nicotineplus-proper

case $1 in
	''   )
		while : ;do
			ping -c1 server.slsknet.org >/dev/null 2>&1 && break
			sleep 1
		done
		# (??) init startup often causes nicotine server reconnects REMEDY: restarting service
		# exec docker --config /home/shum/.docker compose up
		sudo -u shum docker compose up
		;;
	stop )
		# exec docker compose stop
		sudo -u shum docker compose stop || exit 0  # HACK: suppress inconsequential docker reporting
		;;
esac

# kak: filetype=sh
