#!/bin/sh
# sdothum - 2016 (c) wtfpl

server=google.com

pingdaemon() { ping -i15 $server >/dev/null 2>&1 & }

case $1 in
	''   )
		for i in $(seq 1 100) ;do
			ping -c1 $server >/dev/null 2>&1 && { pingdaemon; exit 0; }
			sleep 0.1
		done
		exit 1
		;;
	stop )
		pkill -f "ping .*$server"
		;;
esac

# kak: filetype=sh
