#!/bin/sh
# sdothum - 2016 (c) wtfpl

server=google.com
interface=wlp9s0

ifcheck() {
	while : ;do
		speed=$(ping -c1 $server 2>/dev/null | grep 'time=' | sed -r 's/.*time=(.*)\..* ms/\1/')
		[ ${speed:-100} -ge 100 ] && { ifconfig $interface down; ifconfig $interface up; }
		sleep 10
	done &
}

case $1 in
	''   )
		for i in $(seq 1 100) ;do
			ping -c1 $server >/dev/null 2>&1 && { ifcheck; exit 0; }
			sleep 0.1
		done
		exit 1
		;;
	stop )
		pkill -f "ping .*$server"
		exit 0
		;;
esac

# kak: filetype=sh
