#!/bin/sh
# sdothum - 2016 (c) wtfpl

. /etc/dinit.d/config/postgres.env  # version

. /etc/runit/functions
. /etc/psql${VERSION}/default/postgresql

PGDATA="$PGROOT/data"

# NOTE: service run-as postgres, hence, no need for "su .. -- postgres" (which would syntactically fail)
if [ -z "$(ls -A $PGDATA)" ]; then
	msg "Initializing database in $PGDATA"
	/usr/lib/psql${VERSION}/bin/initdb $INITOPTS -D "$PGDATA" --no-data-checksums 2>&1 || {
		rm -fr "$PGDATA"
		exit 1
	}

	if [ -f /etc/psql${VERSION}/postgresql/postgresql.conf ]; then
		ln -sf /etc/psql${VERSION}/postgresql/postgresql.conf "$PGDATA/postgresql.conf"
	fi
fi

/usr/lib/psql${VERSION}/bin/postgres -D "$PGDATA" $PGOPTS 2>&1

# kak: filetype=sh
