#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="query/winids $@" . $PARENT

# herbstluftwm
# ══════════════════════════════════════════════════════════════════════════════

# .............................................................. List of windows
for i in $(query winids) ;do
	herbstclient attr clients.$i | grep -E 'class =|title ='
done

# kak: filetype=sh
