#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="query/winids $@" . $PARENT

# herbstluftwm
# ══════════════════════════════════════════════════════════════════════════════

# .............................................................. List of winid's

herbstclient foreach C clients. echo C | grep -v focus | cut -d. -f2  # 0x...

# kak: filetype=sh
