#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="background $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ......................................................................... Root

toggle background

# vim: set ft=sh: #
