#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="kill2bwm $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................. Compile 2bwm

term 2bwm 2make

# vim: set ft=sh: #
