#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="filecli $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................. Filemanager

xdotool search --onlyvisible --classname root windowclose || nnn ROOT

# vim: set ft=sh: #
