#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="inspector $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................... Inspect system

menu system

# vim: set ft=sh: #

