#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="invert $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................ Toggle panel contrast

toggle contrast

# vim: set ft=sh: #
