#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="notifypop $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ............................................................. Pop notificaions

dunstctl history-pop

# vim: set ft=sh: #
