#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="twobop $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... 2bwm quit

KAK=/usr/bin/kak
# [ -e /usr/local/bin/kak ] && KAK=/usr/local/bin/kak

# WHY: avoid creating (dead) kak sessions (and non-reusable session IDs) upon exiting Xorg
for i in $($KAK -l) ;do echo kill | $KAK -p ${i%% *} ;done
pkill -f '.*panel.*'  # would be cleared by next x but why wait
killall Xorg

# vim: set ft=sh: #
