#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="scripts $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................. Edit scripts

menu scripts

# vim: set ft=sh: #
