#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="snaplevel $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ........................................................ Snap windows to level

draw snap level

# vim: set ft=sh: #
