#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="snapsmart $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................... Snap smart

# pixel map
width=$(query display width)
winid=$(xdotool getwindowfocus -f)
eval $(xdotool getwindowgeometry --shell $winid)  # WIDTH

# snap to closest edge!
right=$(( $width - ($X + $WIDTH - 1) ))
[ $X -le $right ] && xdotool windowmove $winid 0 y || xdotool windowmove $winid $(( $width - $WIDTH )) y

# vim: set ft=sh: #
