#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="snapright $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................... Snap right

xdotool getwindowfocus -f >/dev/null
xdotool key --delay 25 Super+l        # snap corner
xdotool key --delay 25 Super+Shift+g  # vertical center

# vim: set ft=sh: #
