#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="snapsmart $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... Snap edge

draw snap edge

# vim: set ft=sh: #
