#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="snaptop $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ..................................................................... Snap top

window snap top

# vim: set ft=sh: #
