#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="snapleft $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... Snap left

xdotool getwindowfocus -f >/dev/null
xdotool key --delay 25 Super+p        # snap corner
xdotool key --delay 25 Super+Shift+g  # vertical center

# vim: set ft=sh: #
