#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="wallclock $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# .................................................................... Wallclock

conky clock

# vim: set ft=sh: #
