#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="wallpaper $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ......................................................................... Root

toggle wallpaper

# vim: set ft=sh: #
