#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="west $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................ wmutils focus

closest.sh west

# vim: set ft=sh: #
