#!/usr/bin/dash
# sdothum - 2016 (c) wtfpl
[ $TRACE ] && CHILD="windowsize9 $@" . $PARENT

# 2bwm
# ══════════════════════════════════════════════════════════════════════════════

# ................................................................... Windowsize

menu windowsize 9

# vim: set ft=sh: #
